services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-nginx
    ports:
      - "80:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Descomentar las siguientes líneas para desarrollo con hot-reload
      # - ./index.html:/usr/share/nginx/html/index.html
      # - ./proyectos.html:/usr/share/nginx/html/proyectos.html
      # - ./curriculum.html:/usr/share/nginx/html/curriculum.html
      # - ./Css:/usr/share/nginx/html/Css
      # - ./Js:/usr/share/nginx/html/Js
      # - ./Media:/usr/share/nginx/html/Media
      # - ./assets:/usr/share/nginx/html/assets
      - nginx-logs:/var/log/nginx

volumes:
  nginx-logs:
